version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - network-service

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - network-service
    links:
      - mongo
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - ./.data/mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_DATABASE: dev
    networks:
      - network-service
      
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
    networks:
      - network-service

networks:
  network-service:
    driver: bridge

volumes:
  data:
    driver: local
